### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by z111222333** [L5Player/AutoDriving-Planning-Control-Algorithm-Simulation-Carla#8]
I have some build issues.Please help me to solve these issues, thank you! 
Like this:
[100%] Built target carla_l5player_pid_controller_node                               
Aborted  <<< carla_l5player_pid_controller [6.37s]

Summary: 15 packages finished [18.2s]
  1 package failed: carla_l5player_nop_with_python_script
  10 packages aborted: carla_ackermann_msgs carla_l5player_aeb_with_python_script carla_l5player_lqr_pid_controller carla_l5player_lqr_pid_controller_waypoint carla_l5player_mpc_controller carla_l5player_pid_controller carla_l5player_pid_new_controller carla_l5player_stanley_pid_controller carla_ros_bridge rviz_carla_plugin
  13 packages had stderr output: carla_ad_agent carla_common carla_l5player_aeb_with_python_script carla_l5player_bridge_ego_vis carla_l5player_nop_with_python_script carla_manual_control carla_ros_scenario_runner carla_spawn_objects carla_twist_to_control carla_walker_agent carla_waypoint_publisher ros_compatibility rqt_carla_control
  3 packages not processed

**Comment by z111222333** [comment]
Now, I have a new issues:
[0.555s] ERROR:colcon.colcon_core.extension_point:Exception loading extension 'colcon_core.shell.zsh': cannot import name 'OVERRIDE_OPT' from 'em' (/home/zjq/anaconda3/envs/car0.9/bin/em.py) The Python package 'empy' must be installed and 'em' must not be installed since both packages share the same namespace
Traceback (most recent call last):
  File "/home/zjq/anaconda3/envs/car0.9/lib/python3.8/site-packages/colcon_core/extension_point.py", line 166, in load_extension_points
    extension_type = load_extension_point(name, value, group)
  File "/home/zjq/anaconda3/envs/car0.9/lib/python3.8/site-packages/colcon_core/extension_point.py", line 207, in load_extension_point
    return EntryPoint(name, value, group).load()
  File "/home/zjq/anaconda3/envs/car0.9/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/zjq/anaconda3/envs/car0.9/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zjq/anaconda3/envs/car0.9/lib/python3.8/site-packages/colcon_zsh/shell/zsh.py", line 13, in <module>
    from colcon_core.shell.template import expand_template
  File "/home/zjq/anaconda3/envs/car0.9/lib/python3.8/site-packages/colcon_core/shell/template/__init__.py", line 19, in <module>
    raise e from None
  File "/home/zjq/anaconda3/envs/car0.9/lib/python3.8/site-packages/colcon_core/shell/template/__init__.py", line 10, in <module>
    from em import OVERRIDE_OPT
ImportError: cannot import name 'OVERRIDE_OPT' from 'em' (/home/zjq/anaconda3/envs/car0.9/bin/em.py) The Python package 'empy' must be installed and 'em' must not be installed since both packages share the same namespace
